name: Build prebuilds for single library

on:
  workflow_dispatch:
    inputs:
      lib_name:
        description: "Library name"
        required: true

jobs:
  linux_prebuild:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: linux-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - run: yarn install --frozen-lockfile

      - run: yarn prebuild-lib
        env:
          LIB_NAME: ${{ github.event.inputs.lib_name }}

  windows_prebuild:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: windows-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - run: yarn install --frozen-lockfile

      - run: yarn prebuild-lib
        env:
          LIB_NAME: ${{ github.event.inputs.lib_name }}

  macos_prebuild:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: macos-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - run: yarn install --frozen-lockfile

      - run: yarn prebuild-lib
        env:
          LIB_NAME: ${{ github.event.inputs.lib_name }}

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - linux_prebuild
      - windows_prebuild
      - macos_prebuild
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: linux-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: windows-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - uses: actions/cache@v3
        with:
          path: libs/${{ github.event.inputs.lib_name }}/prebuilds
          key: macos-${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}

      - run: yarn install --frozen-lockfile

      - run: yarn publish-lib
        env:
          LIB_NAME: ${{ github.event.inputs.lib_name }}

  clear_cache:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v3

      - name: Clear cache
        uses: actions/github-script@v6
        env:
          CACHE_KEY: ${{ github.event.inputs.lib_name }}-${{ hashFiles('**/package.json') }}
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const cache of caches.data.actions_caches) {
              if (cache.key === process.env.CACHE_KEY) {
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
              }
            }
            console.log("Clear completed");
