name: Build prebuilds for a package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name"
        required: true
      package_version:
        description: "Package version"
        required: true

env:
  DRY_RUN: "false"

jobs:
  linux_prebuild:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn run pipeline
        env:
          RELEASE_TAG: ${{ github.ref }}
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
          PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PIPELINE: "fetch,patch,deps-installer,build,prepare,test,upload"

  windows_prebuild:
    name: windows
    runs-on: windows-latest
    if: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn run pipeline
        env:
          RELEASE_TAG: ${{ github.ref }}
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
          PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PIPELINE: "fetch,patch,deps-installer,build,prepare,test,upload"

  macos_prebuild:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn run pipeline
        env:
          RELEASE_TAG: ${{ github.ref }}
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
          PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PIPELINE: "fetch,patch,deps-installer,build,prepare,test,upload"

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - linux_prebuild
      # - windows_prebuild
      - macos_prebuild
    steps:
      - run: sleep 10

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn run pipeline
        env:
          RELEASE_TAG: ${{ github.ref }}
          PACKAGE_NAME: ${{ github.event.inputs.package_name }}
          PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PIPELINE: "fetch,patch,publish"
